In [11]:
import pandas as pd
import numpy as np

In [12]:
cluster=pd.read_csv("Cluster Weighting.csv")
matrix=pd.read_csv("Matrix Score.csv")
# user inputs will pull from database
user_inputs = pd.read_csv("user inputs from database.csv")

# get cluster from one or two questions
user_cluser = "Cluster 2"

print(matrix.head())

print(cluster.head())

print(user_inputs.head())

  Category Question  Question_Scale  Weight
0  resorts       Q1               1       0
1  resorts       Q1               2       1
2  resorts       Q1               3       1
3  resorts       Q1               4       1
4  resorts       Q1               5       1
      Group Category     Cluser     Value
0  activity  resorts  Cluster 1  1.749976
1  activity  resorts  Cluster 2  2.708463
2  activity  resorts  Cluster 3  2.641268
3  activity  resorts  Cluster 4  2.214440
4  activity  beaches  Cluster 1  1.733534
  Questions  Answer
0        Q1       1
1        Q2       3
2        Q3       2
3        Q4       4
4        Q5       5

In [13]:
# merge matrix with user answer 
user_scale = matrix.merge(user_inputs, left_on = 'Question', right_on='Questions')
user_scale.head()

  Category Question  Question_Scale  Weight Questions  Answer
0  resorts       Q1               1       0        Q1       1
1  resorts       Q1               2       1        Q1       1
2  resorts       Q1               3       1        Q1       1
3  resorts       Q1               4       1        Q1       1
4  resorts       Q1               5       1        Q1       1

In [14]:
# clean up the merge dataframe and filter out the values only for answers
user_scale = user_scale.loc[user_scale['Question_Scale'] == user_scale['Answer']]
user_scale

           Category Question  Question_Scale  Weight Questions  Answer
0           resorts       Q1               1       0        Q1       1
5          churches       Q1               1       1        Q1       1
10      dance-clubs       Q1               1       1        Q1       1
15    art-galleries       Q1               1       1        Q1       1
20         theatres       Q1               1       1        Q1       1
...             ...      ...             ...     ...       ...     ...
1076    restaurants      Q10               2       1       Q10       2
1081      pubs-bars      Q10               2       0       Q10       2
1086   burger-pizza      Q10               2       0       Q10       2
1091       bakeries      Q10               2       0       Q10       2
1096          cafes      Q10               2       1       Q10       2

[220 rows x 6 columns]

In [15]:
user_scale_total = user_scale.groupby(['Category']).sum(['Value']).drop(columns = ['Question_Scale','Answer'])
user_scale_total

                Weight
Category
art-galleries        5
bakeries             2
beaches              4
beauty-spas          3
burger-pizza         6
cafes                5
churches             8
dance-clubs          7
gardens              5
gyms                 6
juice-bars           5
malls                6
monuments            4
museums              5
parks                3
pubs-bars            5
resorts              5
restaurants          8
swimming-pools       6
theatres             7
view-points          4
zoo                  6

In [20]:
# Merge Cluster with user_scale_total
user_final = cluster.loc[cluster['Cluser']== user_cluser]
user_final_Cat = user_final.merge(user_scale_total, how = "left", left_on = "Category", right_on= "Category")
user_final_Cat['Final_Score_per_Cat'] = user_final_Cat['Value'] * user_final_Cat['Weight']
# user_final_Cat['Total_Score__Cat'] = user_final_Cat.groupby('Group').sum(['Final_Score'])
# top_3 = user_final_Cat.loc[user_final_Cat.groupby('Group')["Final_Score"].idxmax()]
# top_3 = list(top_3["Category"])
top_3

ValueError: Wrong number of items passed 3, placement implies 1

In [17]:
top_3_check = user_final_Cat.sort_values(['Group','Final_Score'],ascending = [True,False])
top_3_check

KeyError: 'Final_Score'